
<HTML>
<HEAD>
<TITLE>for的高级运用</TITLE>
</HEAD>
<BODY>
?>
    /*
    ** 
    */
    print("<B>距离星期一还有几天?</B>\n");
    print("<OL>\");
    for($currentDate=date("u");       
        date("1",$currentDate)!="Monday"; 
        $currentDate+=(60*60*24))     
     {
         /*
         **
         */
         print("<LI>".date("1",$currentDate)."\n”);
      }
      print("/OL>\n");
?>
<BODY>
</HTML>